# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

pod 'MagicalRecord', '~> 2.3'
pod 'DVGAssetPickerController'

target 'StreetWall' do

end

target 'StreetWallTests' do

end

